# Common tasks before building DOMjudge.
---
    - name: set timezone
      timezone:
        name: "{{TIMEZONE}}"

    - name: install common required/useful packages
      tags: packages
      apt: pkg={{item}} state=present update_cache=yes
      with_items:
        - autoconf
        - automake
        - curl
        - git
        - gcc
        - g++
        - make
        - zip
        - unzip
        - php
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - php-json
        - php-xml
        - php-zip
        - php-intl
        - php-mbstring
        - bsdmainutils
        - libcgroup-dev
        - libcurl4-gnutls-dev
        - libjsoncpp-dev
        - libmagic-dev
        - composer
        - debootstrap
        - ack-grep
        - htop
        - ncdu
        - httpie
        - mycli
        - screen
        - qmlscene
        - linuxdoc-tools
        - texlive-latex-recommended
        - texlive-latex-extra
        - texlive-fonts-recommended
        - texlive-lang-european
        - python-pygments
        - collectd

    - name: create domjudge user
      user:
        name: domjudge
        shell: /bin/bash
        groups: sudo
        password: "{{DJ_SHELL_USER_PW}}"

    - name: Add authorized key
      authorized_key:
        user: domjudge
        state: present
        key: "{{DJ_SSH_KEY}}"

    - name: configure git as domjudge user
      become: yes
      become_user: domjudge
      ini_file: dest=/home/domjudge/.gitconfig section=user option="{{item.name}}" value="{{item.value}}"
      with_items:
        - { name: 'email', value: 'team@domjudge.org' }
        - { name: 'name', value: 'DOMjudge @ NWERC' }

    - name: Create .ssh directory
      file: path="/home/domjudge/.ssh" group=domjudge owner=domjudge mode=0700 state=directory

    - name: Create directory for DOMjudge installation
      file: path="{{DJDIR}}" group=domjudge owner=domjudge mode=0755 state=directory

    - name: create working copy from the repo
      become: yes
      become_user: domjudge
      git: repo=https://github.com/DOMjudge/domjudge.git dest={{DJDIR}} version={{GIT_BRANCH}} accept_hostkey=yes update=yes
      register: git_working_copy

    - name: fix permissions on composer directory
      file: path="{{DJDIR}}/lib/vendor/" group=domjudge owner=domjudge recurse=yes

    - name: configure domjudge logging
      copy: src=files/rsyslog.domjudge.conf dest=/etc/rsyslog.d/domjudge.conf

    - name: restart rsyslog service
      service: name=rsyslog enabled=yes state=restarted

    - name: configure domjudge logrotate
      copy: src=files/logrotate.domjudge dest=/etc/logrotate.d/domjudge

    - name: copy DOMjudge logo binary
      copy: src=files/domlogo dest=/home/domjudge/domlogo owner=domjudge group=domjudge mode=0755
