---

- name: setup domserver
  hosts: domserver
  become: yes
  handlers:
    - name: reload systemctl daemon
      systemd: daemon_reload=yes
    - name: restart mysql
      service: name=mysql state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php7.2-fpm
      service: name=php7.2-fpm state=restarted

  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: Enable universe repositories
      lineinfile:
        dest: /etc/apt/sources.list
        state: present
        regexp: "{{item.match}}"
        line: "{{item.line}}"
      with_items:
      - { match: 'bionic universe', line: 'deb http://nl.archive.ubuntu.com/ubuntu bionic universe' }
      - { match: 'bionic-security universe', line: 'deb http://nl.archive.ubuntu.com/ubuntu bionic-security universe' }
      - { match: 'bionic-updates universe', line: 'deb http://nl.archive.ubuntu.com/ubuntu bionic-updates universe' }

    - include: common_tasks_prebuild.yml

    - name: template out the restapi secret file
      template: src=files/restapi.secret-domserver.j2 dest={{DJDIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0640

    - name: template out the dbpasswords secret file
      template: src=files/dbpasswords.secret.j2 dest={{DJDIR}}/etc/dbpasswords.secret owner=domjudge group=domjudge mode=0640

    - name: install domserver required packages
      apt: pkg={{item}} state=present
      with_items:
        - mariadb-server
        - nginx
        - python-mysqldb
        - php-intl
        - php-fpm

    - name: set PHP timezone
      lineinfile:
        dest: /etc/php/7.2/fpm/php.ini
        state: present
        regexp: 'date\.timezone\s*='
        line: 'date.timezone = {{TIMEZONE}}'

    - name: enable php modules
      command: phpenmod {{item}}
      args:
        creates: /etc/php/7.2/fpm/conf.d/20-{{item}}.ini
      with_items:
        - zip
        - intl

    - name: create directory for systemd mysql settings
      file: path=/etc/systemd/system/mysql.service.d/ state=directory

    - name: update systemd so mysql has bigger limits
      copy: src=files/mysql.override.cnf dest=/etc/systemd/system/mysql.service.d/override.conf
      notify:
        - reload systemctl daemon
        - restart mysql

    - name: add mysql config snippet to increase limit
      copy: src=files/mysql.domjudge.cnf dest=/etc/mysql/mysql.conf.d/zz_domjudge.cnf
      notify:
        - reload systemctl daemon
        - restart mysql

    - name: make sure mysql is restarted
      meta: flush_handlers

    - name: Create mysql database
      mysql_db:
        name: "{{DJ_DB_DB}}"
        state: present

    - name: create mysql user
      mysql_user:
        name: "{{DJ_DB_USER}}"
        host: 'localhost'
        password: "{{DJ_DB_PASS}}"
        append_privs: true
        priv: '{{DJ_DB_DB}}.*:ALL'
        state: present

    - include: common_tasks_build.yml

    - name: build domjudge documentation
      become: yes
      become_user: domjudge
      shell: make docs chdir={{DJDIR}}
      when: git_working_copy.changed or dj_configured.changed or not judgedaemon_binary.stat.exists

    - name: copy NWERC executables
      copy:
        src: files/compile-scripts/
        dest: "{{DJDIR}}/sql/files/nwerc"
        owner: domjudge
        group: domjudge

    - name: copy NWERC migration files
      copy:
        src: "{{item.root}}/{{item.path}}"
        dest: "{{DJDIR}}/webapp/src/Migrations/{{item.path}}"
        owner: domjudge
        group: domjudge
      with_filetree: files/migrations
      when: item.state == 'file'

    - name: check if the database is configured
      command: "{{DJDIR}}/bin/dj_setup_database -u root status"
      register: db_status
      ignore_errors: true
      
    - name: make sure the database is configured
      command: "{{DJDIR}}/bin/dj_setup_database -u root bare-install"
      when: "'failed' in db_status.stdout"
      
    - name: upgrade the database
      command: "{{DJDIR}}/bin/dj_setup_database -u root upgrade"
      when: "'failed' not in db_status.stdout"

    - name: clear symfony cache
      become: yes
      become_user: domjudge
      shell: webapp/bin/console cache:clear chdir={{DJDIR}}
      when: git_working_copy.changed or dj_configured.changed or not judgedaemon_binary.stat.exists
