---

- name: setup judgehost
  hosts: judgehost
  become: yes
  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: Set current hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Set permanent hostname
      copy:
        content: "{{ inventory_hostname }}"
        dest: /etc/hostname

    - name: create domjudge-run users
      user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
      with_items:
        - domjudge-run-0
    - name: create domjudge-run group
      group: name=domjudge-run state=present

    - name: disable pc2cancer repo
      lineinfile:
        dest: /etc/apt/sources.list
        regexp: 'pc2cancer'
        state: absent

    - include: common_tasks_prebuild.yml

    - name: template out the restapi secret file
      template: src=files/restapi.secret.j2 dest={{DJDIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0600

    - include: common_tasks_build.yml

    - name: create directory to store .deb's
      file: dest=/root/chroot_debs state=directory owner=root group=root

    - name: download packages we do not have yet locally
      command: "apt download {{ item }}"
      args:
        chdir: /var/cache/apt/archives
        creates: "/var/cache/apt/archives/{{ item }}_*.deb"
      with_items:
        - binutils-common
        - binutils-x86-64-linux-gnu
        - binutils
        - cpp-7
        - cpp
        - gcc-7
        - gcc-7-base
        - gcc
        - icpc-kotlinc
        - libasan4
        - libatomic1
        - libbinutils
        - libcc1-0
        - libcilkrts5
        - libgcc-7-dev
        - libgomp1
        - libisl19
        - libitm1
        - liblsan0
        - libmpc3
        - libmpfr6
        - libmpx2
        - libquadmath0
        - libtsan0
        - libubsan0
        - pypy3-lib
        - pypy3
        - pypy-lib
        - pypy

      # These .deb's are for specific versions of compilers that we copy from the host machine
    - name: copy deb's that need to be installed
      copy:
        src: '/var/cache/apt/archives/{{item}}'
        remote_src: yes
        dest: '/root/chroot_debs/{{item}}'
      with_items:
        - binutils-common_2.30-21ubuntu1~18.04.2_amd64.deb
        - binutils-x86-64-linux-gnu_2.30-21ubuntu1~18.04.2_amd64.deb
        - binutils_2.30-21ubuntu1~18.04.2_amd64.deb
        - cpp-7_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - cpp_4%3a7.4.0-1ubuntu2.3_amd64.deb
        - gcc-7_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - gcc-7-base_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - gcc_4%3a7.4.0-1ubuntu2.3_amd64.deb
        - icpc-kotlinc_1.3.50~icpc_all.deb
        - libasan4_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - libatomic1_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libbinutils_2.30-21ubuntu1~18.04.2_amd64.deb
        - libcc1-0_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libcilkrts5_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - libgcc-7-dev_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - libgomp1_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libisl19_0.19-1_amd64.deb
        - libitm1_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - liblsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libmpc3_1.1.0-1_amd64.deb
        - libmpfr6_4.0.1-1_amd64.deb
        - libmpx2_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libquadmath0_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libtsan0_8.3.0-6ubuntu1~18.04.1_amd64.deb
        - libubsan0_7.4.0-1ubuntu1~18.04.1_amd64.deb
        - openjdk-11-jdk-headless_11.0.4+11-1ubuntu2~18.04.3_amd64.deb
        - openjdk-11-jdk_11.0.4+11-1ubuntu2~18.04.3_amd64.deb
        - openjdk-11-jre-headless_11.0.4+11-1ubuntu2~18.04.3_amd64.deb
        - openjdk-11-jre_11.0.4+11-1ubuntu2~18.04.3_amd64.deb
        - pypy-lib_7.1.1+dfsg-1~ppa1~ubuntu18.04_amd64.deb
        - pypy_7.1.1+dfsg-1~ppa1~ubuntu18.04_amd64.deb
        - pypy3-lib_7.1.1+dfsg-1~ppa1~ubuntu18.04_amd64.deb
        - pypy3_7.1.1+dfsg-1~ppa1~ubuntu18.04_amd64.deb

    - name: create chroot
      shell: "{{DJDIR}}/misc-tools/dj_make_chroot -y -i openjdk-11-jdk -l '/root/chroot_debs/*.deb' 2>&1 | tee /tmp/dj_make_chroot.log"
      args:
        creates: "/chroot/domjudge"
      register: chroot_created

    - name: symlink kotlin binaries
      shell: "chroot /chroot/domjudge ln -s /usr/lib/kotlinc/bin/{{ item }} /usr/bin"
      when: chroot_created.changed
      with_items:
        - kotlin
        - kotlinc
        
    - name: set up default greeter
      shell: "apt install lightdm-webkit-greeter --reinstall -y"
      when: chroot_created.changed
        
    - name: update grub
      shell: "update-grub"
      when: chroot_created.changed

    - name: Reboot after grub change
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: chroot_created.changed

    - name: Wait for the reboot to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: chroot_created.changed

    - name: fix kernel parameters
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'

    - name: install turboboost disable script
      copy:
        src: files/disable-turboboost_ht
        dest: /root/disable_turboboost_ht.sh
        mode: 0755

    - name: copy systemd unit files
      copy: src=files/{{item}}.service dest=/etc/systemd/system/
      tags: updateservice
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: enable and restart the services we just copied
      service: name={{item}} enabled=yes state=restarted
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: autologin domjudge user
      copy: src=files/lightdm-domjudge.conf dest=/etc/lightdm/lightdm.conf.d/domjudge.conf

    - name: make sure autostart directory exists
      file: dest=/home/domjudge/.config/autostart state=directory owner=domjudge group=domjudge
      tags: fix_autostart

    - name: add autostart shortcuts
      copy: src=files/{{item}}.desktop dest=/home/domjudge/.config/autostart/ owner=domjudge group=domjudge mode=0755
      with_items:
        - taillog
        - rotate
        - domjudgelogo

    - name: disable systemd timers
      command: systemctl mask {{item}}
      args:
        creates: /etc/systemd/system/{{item}}
      with_items:
        - apt-daily-upgrade.timer
        - apt-daily.timer
        - systemd-tmpfiles-clean.timer

    - name: copy collectd config
      copy: src=files/collectd.conf dest=/etc/collectd/collectd.conf

    - name: enable and restart collectd
      service: name=collectd enabled=yes state=restarted
